foss-for-synopsys-dwc-arc-processors/newlib

newlib/ChangeLog.ARC
newlib/testsuite/newlib.locale/UTF-8.exp
newlib/testsuite/newlib.stdlib/atexit.exp

Don't run atexit.exp test for boards with GDB. Some ARC boards with GDB break on exit() and return immediately. Thus it's impossible to pass atexit.exp test for these boards.
Don't run UTF-8.exp test if newlib is not built with multibyte support.

Fix UTF-8.exp and atexit.exp tests

---

newlib/ChangeLog.ARC
newlib/libc/sys/arc/syscalls.c

Macros _syscallX are used to implement these system calls.
So it means that in fact functions _stat_r and _times_r are
implemented.
Signed-off-by: Yuriy Kolerov <yuriy.kolerov@synopsys.com>

Add implementaions for system calls stat and times for ARC

---

newlib/ChangeLog.ARC
newlib/libc/machine/arc/memcmp-601.S

The algorithm works incorrectly when sources are aligned. It's necessary to review and fix it later but now just turn off an optimization.
Right now I'm stuck on this heavily optimized and undocumented thing.
STAR: 9000906645
Signed-off-by: Yuriy Kolerov <yuriy.kolerov@synopsys.com>

Fix memcmp for big endian targets

---

libgloss/arc/hl/hl_gettimeofday.c

Clear *tz if specified instead of returning error.

[ARC] [libgloss] Fix hostlink gettimeofday()

---

libgloss/arc64/Makefile.in
libgloss/arc64/arc-main-helper.c
libgloss/arc64/arc-timer.c
libgloss/arc64/arc-timer.h
libgloss/arc64/configure
libgloss/arc64/configure.in
libgloss/arc64/crt0.S
libgloss/arc64/hl-setup.c
libgloss/arc64/hl-stub.c
libgloss/arc64/hl.specs
libgloss/arc64/hl/Makefile.in
libgloss/arc64/hl/hl_api.c
libgloss/arc64/hl/hl_api.h
libgloss/arc64/hl/hl_argc.c
libgloss/arc64/hl/hl_argv.c
libgloss/arc64/hl/hl_clock.c
libgloss/arc64/hl/hl_close.c
libgloss/arc64/hl/hl_exit.c
libgloss/arc64/hl/hl_gettimeofday.c
libgloss/arc64/hl/hl_gw.c
libgloss/arc64/hl/hl_gw.h
libgloss/arc64/hl/hl_isatty.c
libgloss/arc64/hl/hl_lseek.c
libgloss/arc64/hl/hl_open.c
libgloss/arc64/hl/hl_read.c
libgloss/arc64/hl/hl_toolchain.h
libgloss/arc64/hl/hl_unlink.c
libgloss/arc64/hl/hl_write.c
libgloss/arc64/readme-hostlink.md

There is a special interface built in ARC simulators (such as NSIM) called Metaware hostlink IO which can be used to implement system calls.
This commit adds support for this interface to the ARC64 port of libgloss.

Metaware hostlink implementation for ARC64

---

libgloss/arc/readme-hostlink.md

Metaware hostlink doesn't work in nsim if this option is set to
a value other than zero.

[ARC] [libgloss] Add note about nsim_emt to readme

---

libgloss/arc/configure
libgloss/arc/configure.in

host_makefile_frag_path dependency can not be used from
hl folder, because this path is relative to libgloss/arc.
This fix makes host_makefile_frag_path absolute (same as for ARM).

[ARC] [libgloss] Fix build from external path

---

libgloss/arc/dw_uart/device/device_hal/inc/dev_uart.h

The dw_uart build broke with:
Commit 357d7fcc6
In <stdio.h> provide only necessary types
The above commit exposed a latent missing-header bug:
```
In file included from ../../../../../../libgloss/arc/dw_uart/common/console_io.c:40: ../../../../../../libgloss/arc/dw_uart/device/device_hal/inc/dev_uart.h:81:2: error: unknown type name 'uint32_t'
81 |  uint32_t len; /*!< buffer length in bytes */
|  ^~~~~~~~
```
Fix by including <stdint.h>.
Inspired by 90a4ab5eb "Fix nano-malloc build".

Fix dw_uart build

---

newlib/libc/machine/arc64/Makefile.am
newlib/libc/machine/arc64/Makefile.in
newlib/libc/machine/arc64/strcat.S

Created assembly version of strcat with the objective of focusing on speed for larger amounts of memory/bigger strings.
Used measure of speed is instruction count via CPU counters.
Measurements against compiler generated code suggest a decrease in instruction count of around 75%.
Half of this code is based on the newly optimized strlen assembly function.
Newlib DejaGNU tests pass with success!

Optimized strcat implementation

---

newlib/libc/machine/arc64/Makefile.am
newlib/libc/machine/arc64/Makefile.in
newlib/libc/machine/arc64/memmove.S
newlib/libc/machine/arc64/sys/asm.h

Created assembly version of memmove with the objective of focusing on speed for larger amounts of memory
Used measure of speed is instruction count from NSIM, via CPU counters.
Measurements against compiler generated code suggest a decrease in instruction count of ~90% for big memory sizes (200 bytes) and ~30% for smaller ones (14 bytes).
32-bit and 128-bit implementations have slightly smaller, and bigger improvements (respectively)
Newlib dejaGNU tests pass with success

Optimized memmove implementation

---

libgloss/arc/crt0.S
libgloss/arc/dw_uart/arc/arc_exc_asm.S
libgloss/arc64/crt0.S
newlib/libc/machine/arc/setjmp.S
newlib/libc/machine/arc64/setjmp.S

This PR fixes this issue: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/344
Assembler for ARCv2 always extends the name provided by `.file` directive to an absolute form.
On ARCv3 targets `.file` directive forces assembler to put a provided string to `DW_AT_name` field as is without extending to an absolute path. Then GDB cannot find source files because of it.
The best way to fix this issue is just delete lines with `.file` directive in `.S` files and let the compiler to decide what `DW_AT_name` must contain. Particularly, the compiler fills this filed by an absolute path to a `.S` file because only absolute paths are used in toolchain's build process.

arc, arc64: Remove .file directive from .S files

---

libgloss/arc/Makefile.inc

This PR fixes this issue: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/529. Can you please also regenerate `Makefile.in` properly and push? I am not sure that I can do it correctly.

arc: fix typo in libdw_uart sources

---

libgloss/Makefile.in
libgloss/arc/dw_uart/arc/arc_exc_asm.S
libgloss/arc/dw_uart/arc/arc_exception.c

In 2022.09 release for ARC libdw_uart.a is built using a simple Makefile and this library is excluded for all targets except ARC EM. Now Makefile for libgloss is generated using automake scripts and there is no way to to exclude libdw_uart.a for particular targets. And this is a problem because build system tries to build for ARC600 which does not supported interrupt instructions.
Automake and autoconf are not intended to be used in such case when one architecture actually contains 2 different architectures and one library is not supported by both of them. Thus, the easiest way is to force compiler co create stub code for non-EM targets.

Add stub code for dw_uart for non-EM targets 

---

libgloss/arc/nsim-syscalls.c
libgloss/arc64/nsim-syscall.c

Modified the fstat call from stat to fstat
accordingly to semi-hosting syscall.

_fstat: Change stat to fstat call.

---

libgloss/Makefile.in
libgloss/arc64/Makefile.inc

This option makes all read/write operations on volatile data uncached. It was presented earlier but was lost later: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/e26505a062b83d802e2b1b2b8e749b5f7799a160.

arc64: Add missing -mvolatile-di option for MetaWare hostlink 

---

libgloss/arc/arcv2elf-common.ld
libgloss/arc/nsim-syscalls.c
libgloss/arc64/nsim-syscall.c

Don't use `LINKER_VERSION` variable in the linker script - it cannot be recognized by older Binutils. Also, add missing commits from `arc64` branch.

Add missing commits and fix the linker script of boards

---

libgloss/riscv/arcv.ld

Since the newlib implementation of the __libc_init_array() function requires the {preinit,init,fini}_array sections and the corresponding boundary symbols to exist, provide those in arcv.ld in order to be able to use GCC constructor/destructor functions.
This allows us to remove explicit calls to e.g. the init_semihosting() function in user programs.

libgloss: riscv: define init_array-related symbols for ARCV

---

libgloss/riscv/arcv.specs

Modified the arcv.specs file and removed the use
of custom linker script.

arcv.specs: Remove the use of custom linker script.

---

libgloss/Makefile.in
libgloss/riscv/arcv.ld

The linker script for ARC-V aligns the stack on 4-bytes boundary and it leads to undefined behaviour while pushing argument to the stack.
It's necessary to align it on 16-bytes boundary since it's a maximum possible alignment for RISC-V targets according to RISC-V ABI.

Align stack on 16-bytes boundary

---

libgloss/riscv/semihost-sys_exit.c

`SYS_EXIT_EXTENDED` semihosting call allows exiting with an exit code both on 32-bit and 64-bit targets. However, it's not available in the first version of the semihosting specification. Since the first version is pretty old, it may be assumed that semihosting v2 is available and `SYS_EXIT_EXTENDED` may be used.

libgloss: riscv: Use SEMIHOST_exit_extended in semihosting

---

libgloss/Makefile.in
libgloss/riscv/Makefile.inc
libgloss/riscv/semihost-sys_times.c

It's necessary to implement `_times()` in libsemihosting to add support of `clock()` function. `SYS_ELAPSED` and `SYS_TICKFREQ` semihosting calls are used to get a number of ticks which could be compatible with clock() interface and `CLOCKS_PER_SEC` value.
`clock()` function from libc must return value which gives us seconds when it's divided by `CLOCKS_PER_SEC`. By default, `CLOCKS_PER_SEC` is `10**6` for RISC-V. However, semihosting's tick frequency may differ and usually it's `10**9`. Thus, we have to obtain a real value of the tick frequency for the current semihosting setup and calculate a multiplier and use it for adjusting semihosting's number of ticks. E.g., if semihosting's ticks frequency is `10**9` then multiplier is `10**9 / 10**6 = 1000`.
Moreover, I found that Picolibc does …

libgloss: riscv: Add support of clock() for semihosting
